.TH PRINTF 1
.SH NAME
printf \- display characters, strings, and integers on stdout
.SH SYNOPSIS
.B printf
[OPTIONS]
.IR file
[%c characters] [%s strings] [%i or %d integers]
.LP
.B printf
[OPTIONS]
.IR file
[%c characters] [%s strings] [%i or %d integers]
.SH DESCRIPTION
.B printf
printf writes data entered by user to standard output
.br
.SH 1 \- PRINTF
.TP
.BR Example
.br
.SAMPLE



.SH OPTIONS
.TP
.BR \ %s ", " \ %c ", " \ %i ", " \ %d
"s" indicates that user will enter a string.
"c" indicates that user will enter a character.
"i" indicates that user will enter a integer.
"d" indicates that user will enter a interger.
